### ISSUE TITLE
feat: Await after tapOn

### ISSUE THREAD

**Issue by MoezAyadiDev** [wolfenrain/fluttium#28]
In my case after tapping on submit the REST API take time to response.

In my integration test i add duration in pumpAndSettle

`
await tester.pumpAndSettle(const Duration(seconds: 5));
`
<img width="543" alt="Screen Shot 2022-10-14 at 16 13 58" src="https://user-images.githubusercontent.com/94204697/195881961-b09ec89d-7b10-46b3-8c52-c28e9a2ff0bb.png">

If you can adding a separate action to await x seconde, or adding an optional param in onTap

**Comment by wolfenrain** [comment]
Thanks for opening an issue, I am planning on seeing if we can have better detection of such an async action so you wouldn't need to write a custom await yourself, because that shouldn't be the responsibility directly of the user and it can introduce quite a bit of flakiness and slow down your test. Maestro manages this as well for you, dont wait longer than really necessary.

But I will be exposing an await like action in case people do need it, but I would like that action to be more of a last resort for the developer if anything.

**Comment by wolfenrain** [comment]
I have added an enhancement to the internals of the driver that would allow for a timeout on the finding of results (#70), would love to have some eyes and testing on this before I merge it.
