### ISSUE TITLE
fix: Failed to build fluttium_cli:fluttium: Try adding a default case or cases that match 'BrickVariableType.list' 

### ISSUE THREAD

**Issue by udiedrichsen** [wolfenrain/fluttium#302]
**Description**

Fluttium activate is not possible on flutter stable. 

**Steps To Reproduce**

flutter pub global activate fluttium_cli

**Expected Behavior**

Fluttium would be installed.

**Screenshots**

**Additional Context**

pub-cache/hosted/pub.dev/fluttium_cli-0.1.1/lib/src/commands/new_command/new_bundle_command.dart:44:21: Error: The type 'BrickVariableType' is not exhaustively matched by the switch cases since it doesn't match 'BrickVariableType.list'.
 - 'BrickVariableType' is from 'package:mason/src/brick_yaml.dart' ('../../../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/brick_yaml.dart').
Try adding a default case or cases that match 'BrickVariableType.list'.
      switch (props.type) {

**Comment by rohithbb433** [comment]
Even I'm facing similar type of issue.
../../../.pub-cache/hosted/pub.dev/fluttium_cli-0.1.1/lib/src/commands/new_command/new_bundle_command.dart:44:21: Error: The type 'BrickVariableType' is not exhaustively matched by the switch cases since it doesn't match 'BrickVariableType.list'.
 - 'BrickVariableType' is from 'package:mason/src/brick_yaml.dart' ('../../../.pub-cache/hosted/pub.dev/mason-0.1.0-dev.50/lib/src/brick_yaml.dart').
Try adding a default case or cases that match 'BrickVariableType.list'.
      switch (props.type) {

**Comment by mpl** [comment]
Hello,

Is there a work-around for that issue atm? I'm new to flutter and I'd like to try it, but I'm blocked by the same error.

**Comment by the-recondite** [comment]
Hello there, this is a lovely package but unfortunately, we are blocked by this issue. Is there any workaround yet for this?

**Comment by wolfenrain** [comment]
> Hello there, this is a lovely package but unfortunately, we are blocked by this issue. Is there any workaround yet for this?

Planning on publishing a new version with the fix (#305) asap.
